name: PR Build Check

on:
  pull_request:
    branches:
      - master

jobs:
  build_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # match your local version

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build
